# Generated by Django 5.0.1 on 2024-01-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XwordApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_Eng_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('meaning', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='all_Thai_words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('meaning', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='common_word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('meaning1', models.TextField(blank=True)),
                ('meaning2', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_played_words_Eng_meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=255)),
                ('word', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_played_words_Thai_meaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=255)),
                ('word', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Test_class_person',
        ),
    ]
